[package]
name = "alvr_sockets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[features]
# Enables Tracy zones inside socket send when built with alvr_server_core/trace-performance
trace-performance = ["alvr_profiling/tracy"]

[dependencies]
alvr_common.workspace = true
alvr_profiling.workspace = true
alvr_session.workspace = true

bincode = "1"
serde = "1"
serde_json = "1"
socket2 = "0.5"

